tidy:
	@echo "Tidying up..."
	@go mod tidy
start:
	@echo "Starting the engine..."
	@go run .
generate-api:
	@echo "Generating API code..."
	@goctl api go --api engine.api -dir .

	http://docker.m.daocloud.io


curl "https://docker.hlmirror.com/token?service=registry.docker.io&scope=repository:library/redis:pull"